#!/usr/bin/env node

// Generates unicodejs.*.testdata.js from Unicode test data

const VERSION = '12.1.0',
	http = require( 'http' ),
	fs = require( 'fs' );

function buildTests( body, jsname ) {
	var js, filename,
		output = [],
		lines = body.split( /\n/ );

	lines.forEach( function ( line ) {
		var parts = line.split( '#' );
		if ( !parts[ 0 ] ) {
			return;
		}
		output.push( line );
	} );

	// Write js file
	js = '// This file is GENERATED by tools/unicodejs-tests.js\n' +
		'// DO NOT EDIT\n' +
		'unicodeJS.testdata.' + jsname + ' = ' + JSON.stringify( output, null, '\t' ).replace( /"/g, '\'' ) + ';\n';

	filename = __dirname + '/../tests/unicodejs.' + jsname + '.testdata.js';
	fs.writeFile( filename, js );
	console.log( 'wrote ' + filename );
}

[
	{
		url: 'http://www.unicode.org/Public/%V/ucd/auxiliary/WordBreakTest.txt',
		jsname: 'wordbreak'
	},
	{
		url: 'http://www.unicode.org/Public/%V/ucd/auxiliary/GraphemeBreakTest.txt',
		jsname: 'graphemebreak'
	}
].forEach( function ( options ) {
	var request = http.get( options.url.replace( '%V', VERSION ), function ( res ) {
		var body = '';

		res.setEncoding( 'utf8' );

		res.on( 'data', function ( data ) {
			body += data;
		} );

		res.on( 'end', function () {
			buildTests( body, options.jsname );
		} );
	} );
	request.end();
} );
